#! /bin/bash 

PKG_name="web.sh"

declare -A PKG_distro_include

PKG_distro_include["Debian"]="yes"
PKG_distro_include["Arch"]="yes"
PKG_distro_include["RedHat"]="yes"
PKG_distro_include["openSUSE"]="yes"


declare -a PKG_dependencies

PKG_dependencies=(sed)

PKG_distro_package_name["Debian","sed"]="sed"
PKG_distro_package_name["Arch","sed"]="sed"
PKG_distro_package_name["RedHat","sed"]="sed"
PKG_distro_package_name["openSUSE","sed"]="sed"

